name: Run Tests

on:
  push:
    branches:
      - '**' 
  pull_request:
    branches:
      - main
      - 'release/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  run_tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y make libfontconfig1-dev pkg-config

      - name: Run tests
        run: make test